import 'server-only';

import { asc, desc, eq } from 'drizzle-orm';

import { db, type Tx } from '@/db/client';
import { customer, order, orderLine, payment, slot } from '@/db/schema';
import type { OrderStatus } from '@/domain/types';

/**
 * Reading an order back, for the customer.
 *
 * ⭐ THE TOKEN IS THE CREDENTIAL. `/orders/[token]` has no login and asks for
 * no identity: the unguessable link IS the authorisation. That is not a
 * prototype shortcut, it is the right long-term shape. It works for a customer
 * with no account, on a borrowed phone, from a link in an email, and it is
 * what every delivery company does.
 *
 * `public_token` is a v4 UUID, so 122 bits of randomness. It is not guessable
 * and it is generated by a column DEFAULT so no code path can create an order
 * without one.
 *
 * ⚠ WHAT THIS DELIBERATELY DOES NOT RETURN: the customer's phone number, their
 * email, or the order's internal id. Anyone holding the link can see the
 * order; nobody holding the link should learn how to contact its owner or
 * address another API with its id.
 */

export interface TrackedLine {
  readonly productName: string;
  readonly requestedG: number;
  readonly actualG: number | null;
  readonly estAmountCents: number;
  readonly actAmountCents: number | null;
  readonly isEstimate: boolean;
}

export interface TrackedOrder {
  readonly publicToken: string;
  readonly status: OrderStatus;
  readonly placedAtMs: number;
  readonly slotStartsAtMs: number;
  readonly slotEndsAtMs: number;
  readonly addressLine1: string;
  readonly addressLine2: string | null;
  readonly city: string;
  readonly province: string;
  /** Null for an order located by coordinates. Both cannot be absent. */
  readonly postalCode: string | null;
  /**
   * Where the customer's device said they were, if it said. Six decimals,
   * carried as strings all the way to the view for the reason the repository
   * writes strings: a `numeric` is not a double and is not treated as one.
   */
  readonly lat: string | null;
  readonly lng: string | null;
  readonly deliveryNotes: string | null;
  readonly estLineTotalCents: number;
  readonly deliveryFeeCents: number;
  readonly estTotalCents: number;
  readonly finalTotalCents: number | null;
  /** The ceiling actually held. Null when nothing was authorised. */
  readonly authorisedCents: number | null;
  readonly capturedCents: number | null;
  /** ⚠ `'stub'` means no money moved. The UI banner keys off this. */
  readonly paymentProvider: string | null;
  /**
   * ⚠ HOW IT IS BEING PAID, WHICH IS NOT THE SAME QUESTION AS WHETHER MONEY
   * MOVED. `COD` means there is no `payment` row at all, so every field above
   * is null for a perfectly healthy cash order; reading "no authorisation" as
   * "payment failed" is exactly the conflation `CLAUDE.md` forbids.
   */
  readonly payMode: 'PREPAID' | 'COD';
  /**
   * What the driver reported collecting at the door. Only ever set on a
   * delivered cash order, and only when it EQUALS the final total — the
   * `order_cod_settled_on_delivery` CHECK is what makes that true rather than
   * a convention.
   */
  readonly cashCollectedCents: number | null;
  readonly lines: readonly TrackedLine[];
}

export async function orderByPublicToken(
  token: string,
  tx: Tx | typeof db = db,
): Promise<TrackedOrder | null> {
  const rows = await tx
    .select({
      id: order.id,
      publicToken: order.publicToken,
      status: order.status,
      createdAt: order.createdAt,
      addressLine1: order.addressLine1,
      addressLine2: order.addressLine2,
      city: order.city,
      province: order.province,
      postalCode: order.postalCode,
      lat: order.lat,
      lng: order.lng,
      deliveryNotes: order.deliveryNotes,
      estLineTotalCents: order.estLineTotalCents,
      deliveryFeeCents: order.deliveryFeeCents,
      estTotalCents: order.estTotalCents,
      finalTotalCents: order.finalTotalCents,
      payMode: order.payMode,
      cashCollectedCents: order.cashCollectedCents,
      slotStartsAt: slot.startsAt,
      slotEndsAt: slot.endsAt,
    })
    .from(order)
    .innerJoin(slot, eq(slot.id, order.slotId))
    .where(eq(order.publicToken, token))
    .limit(1);

  const row = rows[0];
  if (row === undefined) return null;

  const [lines, payments] = await Promise.all([
    tx
      .select({
        productName: orderLine.productName,
        requestedG: orderLine.requestedG,
        actualG: orderLine.actWeightG,
        estAmountCents: orderLine.estAmountCents,
        actAmountCents: orderLine.actAmountCents,
        pricingMode: orderLine.pricingMode,
      })
      .from(orderLine)
      .where(eq(orderLine.orderId, row.id))
      .orderBy(asc(orderLine.productName)),
    tx
      .select({
        provider: payment.provider,
        authorisedCents: payment.authorisedCents,
        capturedCents: payment.capturedCents,
      })
      .from(payment)
      .where(eq(payment.orderId, row.id))
      .limit(1),
  ]);

  const pay = payments[0];

  return {
    publicToken: row.publicToken,
    status: row.status,
    placedAtMs: row.createdAt.getTime(),
    slotStartsAtMs: row.slotStartsAt.getTime(),
    slotEndsAtMs: row.slotEndsAt.getTime(),
    addressLine1: row.addressLine1,
    addressLine2: row.addressLine2,
    city: row.city,
    province: row.province,
    postalCode: row.postalCode,
    lat: row.lat,
    lng: row.lng,
    deliveryNotes: row.deliveryNotes,
    estLineTotalCents: row.estLineTotalCents,
    deliveryFeeCents: row.deliveryFeeCents,
    estTotalCents: row.estTotalCents,
    finalTotalCents: row.finalTotalCents,
    payMode: row.payMode,
    cashCollectedCents: row.cashCollectedCents,
    authorisedCents: pay?.authorisedCents ?? null,
    capturedCents: pay?.capturedCents ?? null,
    paymentProvider: pay?.provider ?? null,
    lines: lines.map((l) => ({
      productName: l.productName,
      requestedG: l.requestedG,
      actualG: l.actualG,
      estAmountCents: l.estAmountCents,
      actAmountCents: l.actAmountCents,
      isEstimate: l.pricingMode === 'perKg',
    })),
  };
}

/**
 * A customer's recent orders, by phone.
 *
 * ⚠ THIS IS THE UNVERIFIED PATH, and it is why `/orders` sits behind a code
 * while `/orders/[token]` does not. Anyone who knows a number could ask for
 * this list, so the route that calls it must gate on the verifier first, and
 * the verifier must be impossible to stub in production.
 *
 * Returns tokens, not ids: the list links to the token pages, which keeps one
 * credential in the system rather than two.
 */
export async function recentOrdersForPhone(
  phoneE164: string,
  limit = 20,
  tx: Tx | typeof db = db,
): Promise<readonly { publicToken: string; status: OrderStatus; placedAtMs: number; estTotalCents: number; finalTotalCents: number | null }[]> {
  const rows = await tx
    .select({
      publicToken: order.publicToken,
      status: order.status,
      createdAt: order.createdAt,
      estTotalCents: order.estTotalCents,
      finalTotalCents: order.finalTotalCents,
    })
    .from(order)
    .innerJoin(customer, eq(customer.id, order.customerId))
    .where(eq(customer.phone, phoneE164))
    .orderBy(desc(order.createdAt))
    .limit(limit);

  return rows.map((r) => ({
    publicToken: r.publicToken,
    status: r.status,
    placedAtMs: r.createdAt.getTime(),
    estTotalCents: r.estTotalCents,
    finalTotalCents: r.finalTotalCents,
  }));
}
